name: 'Checkout Bullet Train Core Repo'
description: 'Checks out the Bullet Train Core Repo'
inputs:
  target_dir:
    description: 'The directory where the core repo should be placed'
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Create Target Dir
      run: mkdir -p ${{ inputs.target_dir }}
      shell: bash

    - run: pwd
      working-directory: ${{ inputs.target_dir }}
      shell: bash
    - run: ls -al
      working-directory: ${{ inputs.target_dir }}
      shell: bash

    - name: Test a script
      working-directory: ${{ github.action_path }}
      run: ./checkout-core-repo.sh
      shell: bash
      env:
        TARGET_BRANCH: ${{ github.head_ref }}
        TARGET_DIR: ${{ format('{0}/{1}', github.workspace, inputs.target_dir) }}

    - run: pwd
      working-directory: ${{ inputs.target_dir }}
      shell: bash
    - run: ls -al
      working-directory: ${{ inputs.target_dir }}
      shell: bash


