name: 'Checkout Bullet Train Core Repo'
description: 'Checks out the Bullet Train Core Repo'

runs:
  using: "composite"
  steps:
    - name: Just a test
      run: echo "just testing"
      shell: bash
    - run: pwd
      working-directory: ${{ github.action_path }}
      shell: bash
    - run: ls -al
      working-directory: ${{ github.action_path }}
      shell: bash
    - name: Test a script
      working-directory: ${{ github.action_path }}
      run: checkout-core-repo.sh
      shell: bash


