name: 'Checkout Bullet Train Core Repo'
description: 'Checks out the Bullet Train Core Repo'

runs:
  using: "composite"
  steps:
    - name: Just a test
      run: echo "just testing"
      shell: bash
    - name: Test a script
      run: checkout-core-repo.sh
      shell: bash


