name: 'Checkout Bullet Train Starter Repo'
description: 'Checks out the Bullet Train Starter Repo'

runs:
  using: "composite"
  steps:
    - name: Just a test
      run: echo "just testing"
      shell: bash


