name: 'Link the Core Repo'
inputs:
  application_dir:
    description: 'The directory where the starter repo lives'
    required: true
    type: string
  core_dir:
    description: 'The directory to link'
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - run: pwd
      working-directory: ${{ inputs.application_dir }}
      shell: bash
    - run: ls -al
      working-directory: ${{ inputs.application_dir }}
      shell: bash

    - name: Link local repos
      working-directory: ${{ github.action_path }}
      run: ./link-repo.sh
      shell: bash
      env:
        APPLICATION_DIR: ${{ inputs.application_dir }}
        CORE_DIR: ${{ inputs.core_dir }}
        WORKSPACE: ${{ github.workspace }}

    - run: pwd
      working-directory: ${{ inputs.application_dir }}
      shell: bash
    - run: ls -al
      working-directory: ${{ inputs.application_dir }}
      shell: bash


