name: 'Checkout Repo with matching branch'
description: 'Checks out a repo, trying to get the branch that matches the name of the current branch'
inputs:
  target_dir:
    description: 'The directory where the core repo should be placed'
    required: true
    type: string
  repository:
    description: 'The repo to be checked out'
    required: true
    type: string
  target_branch:
    description: 'The branch to try to match'
    required: true
    default: ${{ github.head_ref }}
    type: string
  default_branch:
    description: 'The branch to use if a match is not found'
    required: true
    default: main
    type: string

runs:
  using: "composite"
  steps:
    - name: Look for matching branch
      working-directory: ${{ github.action_path }}
      run: ./determine-branch.sh
      shell: bash
      id: determine-branch
      env:
        REPOSITORY: ${{ inputs.repository }}
        TARGET_BRANCH: ${{ inputs.target_branch }}
        DEFAULT_BRANCH: ${{ inputs.default_branch }}

    - name: Check branch output
      run: echo "${{ steps.determine-branch.outputs.BRANCH_TO_CHECKOUT }}"
      shell: bash

    - uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repository }}
        path: ${{ inputs.target_dir }}
        ref: ${{ steps.determine-branch.outputs.BRANCH_TO_CHECKOUT }}
